version: '3.3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot
    environment:
      - BOT_TOKEN=6004504657:AAEk0sk69zTH8EP1WuleOhnOU4_qJ3Ig6p4
    ports:
      - 8080:8080
    depends_on:
      - tarantool

  tarantool:
    image: tarantool/tarantool:latest
    container_name: tarantool
    command: tarantool db/init.lua
